# Generated by Django 5.1.3 on 2024-11-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_bb_price_alter_bb_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
    ]
