# Generated by Django 5.1.3 on 2024-11-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_bb_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='comment',
        ),
    ]
