# Generated by Django 5.1.2 on 2024-11-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_options_alter_bb_order_with_respect_to'),
        ('bboard', '0004_remove_bb_comment'),
    ]

    operations = [
    ]
