# Generated by Django 5.1.2 on 2025-02-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_alter_rubric_options_rubric_order_alter_bb_price'),
        ('bboard', '0006_alter_rubric_options_rubric_order_alter_bb_price'),
    ]

    operations = [
    ]
