# Generated by Django 5.1.2 on 2025-02-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_merge_20250222_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
    ]
