# Generated by Django 5.1.2 on 2025-02-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_revrubric'),
        ('bboard', '0008_revrubric'),
    ]

    operations = [
    ]
