# Generated by Django 5.1.2 on 2025-02-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_bb_img'),
        ('bboard', '0009_merge_0006_revrubric_0008_revrubric'),
    ]

    operations = [
    ]
