# Generated by Django 5.1.2 on 2024-12-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_spare_advuser_machine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemList',
        ),
    ]
