# Generated by Django 5.1.2 on 2025-02-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_message_privatemessage'),
        ('testapp', '0004_delete_itemlist'),
    ]

    operations = [
    ]
