# Generated by Django 5.1.2 on 2025-02-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_merge_20250222_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': []},
        ),
        migrations.AlterField(
            model_name='machine',
            name='spares',
            field=models.ManyToManyField(through='testapp.Kit', to='testapp.spare'),
        ),
    ]
