# Generated by Django 5.1.2 on 2025-02-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_message_options_alter_privatemessage_options'),
        ('testapp', '0006_alter_message_options_alter_privatemessage_options_and_more'),
    ]

    operations = [
    ]
