# Generated by Django 5.1.2 on 2025-02-23 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_merge_20250222_1400'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.IntegerField(verbose_name='Количество на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='user',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('hide_comments', 'Можно скрывать комментарии'),),
            },
        ),
        migrations.CreateModel(
            name='ElectronicProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.product')),
                ('warranty_months', models.IntegerField(default=12, verbose_name='Гарантия (месяцы)')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('power_consumption', models.FloatField(verbose_name='Потребляемая мощность (Вт)')),
            ],
            options={
                'verbose_name': 'Электронный продукт',
                'verbose_name_plural': 'Электронные продукты',
            },
            bases=('testapp.product',),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('electronicproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.electronicproduct')),
                ('screen_size', models.FloatField(verbose_name='Размер экрана (дюймы)')),
                ('battery_capacity', models.IntegerField(verbose_name='Емкость батареи (мАч)')),
                ('os', models.CharField(max_length=50, verbose_name='Операционная система')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
            },
            bases=('testapp.electronicproduct',),
        ),
    ]
